const theme = {
    primary:"#df691a",
    primaryVariant:"#a74f13",
    secondary:"#2b3e50",
    secondaryVariant:"#a74f13",
    tertiary:"#d1332e",
    text:{
        default:"black",
        primary:"#1a1a1a",
        primaryVariant:"black",
        secondary:"#666666"
    },
    header:{
        background:"#df691a",
        text:{
            primary:"#fff",
            secondary:"#E6E6E6"
        }
    },
    background:{
        default:"pink",
        primary:"white",
        primaryVariant:"#f4f4f4",
        secondary:"#e9e9ef",
        body:null
    },/*
    surface:{
        default:"#f4f4f4",
    },*/
    tabBar:{
        background:"white",
        backgroundVariant:"#e6e6e6",
        button:"black",
        text:"black",
        textVariant:"#000000"
    },
    button:{
        primary:"#70a1b8",
        secondary:"#0F5B9A",
        tertiary:"#2b3e50",
    },
    link:{
        primary:"#70a1b8",
        secondary:"#0F5B9A",
        tertiary:"#2b3e50",
    },
    social:{
        reddit:"#ff4500",
        facebook:"#4267b2",
        discord:"#7289da",
        twitter:"#1da1f2",
        patreon:"#f96854"
    },
    share:"#2b3e50"
}

export default theme;