const theme = {
    primary:"#df691a",
    primaryVariant:"#a74f13",
    secondary:"#476785",
    secondaryVariant:"#7a9ab8",
    tertiary:"#d1332e",
    text:{
        default:"white",
        primary:"#e5e5e5",
        primaryVariant:"white",
        secondary:"#999999"
    },
    header:{
        background:"#df691a",
        text:{
            primary:"#fff",
            secondary:"#E6E6E6"
        }
    },
    background:{
        default:"pink",
        primary:"#000",
        primaryVariant:"#333333",
        secondary:"#161610",
        body:""
    },
    surface:{
        default:"#f4f4f4",
    },
    tabBar:{
        background:"#666666",
        button:"white",
        text:"white"
    },
    button:{
        primary:"#70a1b8",
        secondary:"#0F5B9A",
        tertiary:"#2b3e50",
    },
    link:{
        primary:"#70a1b8",
        secondary:"#0F5B9A",
        tertiary:"#2b3e50",
    },
    social:{
        reddit:"#ff4500",
        facebook:"#4267b2",
        discord:"#7289da",
        twitter:"#1da1f2",
        patreon:"#f96854"
    },
    share:"#2b3e50"
}

export default theme;